### ISSUE TITLE
Can I contribute to this Repo?

### ISSUE THREAD

**Issue by rahulkapoor90** [VinayGupta23/VITacademics_Windows#1]

**Comment by aneesh-neelam** [comment]
Sure. 

Learn how to use Git and GitHub properly if you don't already know. 

Ask @VinayGupta23 for more information regarding the Windows app.

**Comment by rahulkapoor90** [comment]
Okay.

**Comment by rahulkapoor90** [comment]
@VinayGupta23 what you say?

**Comment by VinayGupta23** [comment]
Yeah sure. You're familiar with Git/Github right?

Let me just get back to you in the evening, am busy now.

Sent from my Windows Phone

**Comment by rahulkapoor90** [comment]
Okay! Nice and yes I am familiar with GitHub.

**Comment by VinayGupta23** [comment]
Thats nice.

@rahulkapoor90  It would be preferable if you could go through the library and API built for the Windows app development, so you can have an idea of how the app back-end works. They can be found under the following projects:
1. [AcademicsSupportLibrary](https://github.com/VinayGupta23/VITacademics_Windows/tree/master/AcademicsSupportLibrary)
2.  [VITacademics.Shared](https://github.com/VinayGupta23/VITacademics_Windows/tree/phoneDev/VITacademics/VITacademics.Shared)

**Comment by rahulkapoor90** [comment]
Yeah. I was already going through your that.
 It's nice that it is going to be built for both windows and phone but keep windows 10 in mind while making the Windows one.

**Comment by VinayGupta23** [comment]
Yeah, I know. We are hoping that there are not going to be major API changes and anyways we will be upgrading the app as soon as possible after Windows 10 releases officially.

**Comment by rahulkapoor90** [comment]
Nice. Tell me if you want any contribution, I'll continue watching this Repo and point any bugs if i find.
