### ISSUE TITLE
Adding noUI Slider for windows phone?

### ISSUE THREAD

**Issue by rahulkapoor90** [VinayGupta23/VITacademics_Windows#2]
The current VITacademics app (in Store) looks bad when slider comes when scrolling in attendance & today panaroma item, how about adding NoUI Slider  here :- https://github.com/leongersen/noUiSlider

**Comment by aneesh-neelam** [comment]
@rahulkapoor90: You must understand that this is a complete rewrite.

**Comment by rahulkapoor90** [comment]
yeah, i know that. i am just suggesting necessary changes.

**Comment by VinayGupta23** [comment]
Moreover, we are not using any third party tools. All dependencies are built from the ground up if required.

**Comment by rahulkapoor90** [comment]
okay. I get that.
