### ISSUE TITLE
Suggested UX Enhancement - Displaying attendance details in descending order of date

### ISSUE THREAD

**Issue by kishore-narendran** [VinayGupta23/VITacademics_Windows#3]
In the course details pane of the application when displaying the attendance details, consider displaying the attendance details in descending order of date. My reasoning for the same is simple - people are more likely to check for their attendance status on recent classes than on older classes, subsequently scrolling to find the newest class would be unnecessary. 

For information, I am referring to the details section at the bottom of the screenshot I have posted below.

![](https://dl.pushbulletusercontent.com/EoHfZmBiuLI2kh4ml24NxqsZlyAOCgOa/wp_ss_20150404_0001.jpg)

**Comment by VinayGupta23** [comment]
Yes you're right. Its updated now.
