### ISSUE TITLE
UI Bug - Word wrapping the title of the project in additional details

### ISSUE THREAD

**Issue by kishore-narendran** [VinayGupta23/VITacademics_Windows#4]
Apply some form of word wrapping/line breaking to show the entire project title in the additional details section for the project course and other related courses. Have a look at the following screenshot for more information.

![](https://dl.pushbulletusercontent.com/07GYK5idcgQdxfPBcunHtRZt8n91mq2j/wp_ss_20150404_0002.jpg)

**Comment by VinayGupta23** [comment]
Fixed.
