### ISSUE TITLE
Branches and Tags

### ISSUE THREAD

**Issue by aneesh-neelam** [VinayGupta23/VITacademics_Windows#5]
[Branches](https://github.com/VinayGupta23/VITacademics_Windows/branches) are used for development many different modules independently or concurrently. [Releases](https://github.com/VinayGupta23/VITacademics_Windows/releases) are used to tag a particular commit as a specific release. 

Should use Branches for different Releases only if you have multiple versions pushed out.

**Comment by VinayGupta23** [comment]
Oh. I didn't even know there was a feature to mark releases on commits.
Then I'll cleanup the repository branches asap.

**Comment by VinayGupta23** [comment]
Wait, so when in your repository it shows 0.12 release and so on, they are all release tags and not separate branches?

**Comment by aneesh-neelam** [comment]
No, that was me pushing updates to the release build and the development build simultaneously. However, that is no longer necessary. 

You can check out the [VITacademics](https://vitacademics-rel.herokuapp.com/) releases [here](https://github.com/aneesh-neelam/VITacademics/releases).

**Comment by VinayGupta23** [comment]
Okay so those branches are effectively stale now?

Alright so I should move all releases to the release tags right?

**Comment by aneesh-neelam** [comment]
Yeah. 

And those branches are stale. I keep them around for nostalgic purposes. 
Although I can checkout from release tags as well.

**Comment by VinayGupta23** [comment]
Oh okay. In that case I might keep one or two for nostalgic purposes as well :P
I know Github gives that feel when you're looking around the site.

**Comment by aneesh-neelam** [comment]
Oh great.

**Comment by VinayGupta23** [comment]
Haha :P
